@startuml
left to right direction
actor Arbitre as a
package PingPong {
    usecase "Demarrer une partie" as UC1
    usecase "Demarrer un nouveau set" as UC2
    usecase "Attribuer des points" as UC3
}
a --> UC1
a--> UC2
a --> UC3
@enduml